name: Lambda Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Build
      run: |
        pwd
        yarn
        ls build
        yarn build
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy functions to Lambda
      env:
        DYNAMO_DB_TABLE: ${{ secrets.DYNAMO_DB_TABLE }}
      run: |
        node build/deploy.js